# main.py
import pandas as pd
import datetime
from pathlib import Path
import sys
from openpyxl import load_workbook
from openpyxl.styles import Alignment

# --- CSVから stock_codes_list.py を生成する関数 ---
def update_stock_codes_list_file(csv_file_path):
    output_filename = "stock_codes_list.py"
    try:
        df = pd.read_csv(csv_file_path, header=None)
        stock_codes = df[0].astype(str).tolist()
        print(f"\n{csv_file_path} から {len(stock_codes)} 件の銘柄コードを読み込みました。")
        
        with open(output_filename, 'w', encoding='utf-8') as f:
            f.write("# stock_codes_list.py\n")
            f.write(f"# Generated by main.py on {datetime.date.today()}\n")
            f.write("STOCK_CODES_LIST = [\n")
            for code in stock_codes:
                f.write(f'    "{code.strip()}",\n')
            f.write("]\n")
        
        print(f"★★★ 成功: {output_filename} を更新しました。 ★★★")
        return True
        
    except FileNotFoundError:
        print(f"エラー: CSVファイル '{csv_file_path}' が見つかりません。")
        return False
    except Exception as e:
        print(f"CSV読み込みエラー: {e}")
        return False

# --- メイン処理 ---
def main():
    if len(sys.argv) < 2:
        print("------------------------------------------------")
        print("エラー: 読み込むCSVファイル名を指定してください。")
        print("実行例: python main.py asean_list.csv")
        print("------------------------------------------------")
        return

    csv_file_to_load = sys.argv[1]
    
    if not update_stock_codes_list_file(csv_file_to_load):
        return

    try:
        import stock_codes_list
        import yfinance_client
        import data_processor
    except ImportError as e:
        print(f"モジュールインポートエラー: {e}")
        return

    print("=== ASEAN株 財務データ取得システム (Yahoo Finance版) ===")
    
    codes = stock_codes_list.STOCK_CODES_LIST
    print(f"取得対象: {len(codes)} 銘柄")
    
    all_results = []

    for code in codes:
        print(f"\n--- {code} の処理中 ---")
        
        raw_data = yfinance_client.get_stock_data(code)
        
        if raw_data:
            processed_data = data_processor.extract_data(code, raw_data)
            all_results.append(processed_data)
            
            print(f"  会社名: {processed_data.get('Name of Company')}")
            print(f"  売上高: {processed_data.get('REVENUE')}")
        else:
            print("  データの取得に失敗しました。")

    # --- Excel保存処理 ---
    if all_results:
        print("\nExcelファイルを作成しています...")
        df = pd.DataFrame(all_results)
        
        # 1. 基本的な整形
        df = data_processor.format_for_excel(df)
        
        # 2. 不要な列を削除
        if "Sector /Industry" in df.columns:
            df = df.drop(columns=["Sector /Industry"])
            
        # 3. 指定された順番に並べ替え & 空列の追加
        df["Ref"] = range(1, len(df) + 1)

        empty_cols = [
            "ShareInvestor Category Classification", "Taka's comments", "Remarks", 
            "Listed 'o' / Non Listed \"x\"", "Visited (V) / Meeting Proposal (MP)", 
            "Segments", "Access", "Last Communications", 
            "Number of Employee Previous (in 2024)", "Number of Employee Previous", 
            "Incorporated (IN / Year)", "Category Classification SGX", "Sector /Industry SGX"
        ]
        for col in empty_cols:
            df[col] = ""
            
        df["Listed 'o' / Non Listed \"x\""] = "o"
        df["ShareInvestor Category Classification"] = df["Category Classification/ShareInvestor"]
        
        # 3-4. 指定された列順を定義 (Current/Non-Current Loan 削除済み)
        target_order = [
            "Ref",
            "Name of Company",
            "ShareInvestor Category Classification",
            "Taka's comments",
            "Code",
            "Currency",
            "Exchange Rate (to SGD)",
            "Remarks",
            "Listed 'o' / Non Listed \"x\"",
            "Visited (V) / Meeting Proposal (MP)",
            "Website",
            "Major Shareholders",
            "FY",
            "REVENUE (Mil)",
            "Segments",
            "PROFIT (Mil)",
            "GROSS PROFIT (Mil)",
            "OPERATING PROFIT (Mil)",
            "NET PROFIT (Group) (Mil)",
            "NET PROFIT (Shareholders) (Mil)",
            "Minority Interest (Mil)",
            "Shareholders' Equity (Mil)",
            "Total Equity (Mil)",
            "TOTAL ASSET (Mil)",
            "Debt/Equity(%)",
            "Loan (Mil)",
            "Loan/Equity (%)",
            "Summary of Business",
            "Chairman / CEO",
            "Address",
            "Contact No.",
            "Access",
            "Last Communications",
            "Number of Employee",
            "Number of Employee Previous (in 2024)",
            "Number of Employee Previous",
            "Category Classification/ShareInvestor",
            "Sector & Industry ShareInvestor",
            "Incorporated (IN / Year)",
            "Category Classification SGX",
            "Sector /Industry SGX"
        ]
        
        # 列順の適用
        df = df.reindex(columns=target_order)
        df = df.rename(columns={"Number of Employee": "Number of Employee Current"})

        # ファイル名生成
        today = datetime.date.today().strftime("%Y-%m-%d")
        base_name = f"asean_financial_data_{today}"
        filename = f"{base_name}.xlsx"
        
        counter = 1
        while Path(filename).exists():
            filename = f"{base_name}_{counter}.xlsx"
            counter += 1
            
        try:
            # 1. まず保存
            df.to_excel(filename, index=False)
            
            # 2. openpyxlで開いて書式設定
            wb = load_workbook(filename)
            ws = wb.active
            
            right_align = Alignment(horizontal='right')
            
            for cell in ws[1]:
                col_name = str(cell.value)
                col_idx = cell.column
                
                number_format = None
                apply_alignment = False
                
                if "(Mil)" in col_name:
                    number_format = '#,##0.000'
                    apply_alignment = True
                elif "(%)" in col_name or "%" in col_name:
                    number_format = '0.00%'
                    apply_alignment = True
                elif col_name == "FY":
                    apply_alignment = True
                
                if number_format or apply_alignment:
                    for row in ws.iter_rows(min_row=2, min_col=col_idx, max_col=col_idx):
                        for cell in row:
                            if apply_alignment:
                                cell.alignment = right_align
                            if number_format:
                                cell.number_format = number_format
            
            wb.save(filename)
            print(f"★★★ 成功: {filename} に保存しました (書式設定・右揃え適用完了) ★★★")
            
        except Exception as e:
            print(f"エラー: Excel保存に失敗しました ({e})")
            
    else:
        print("保存するデータがありませんでした。")

if __name__ == "__main__":
    main()